---
- name: Install Storefront Pre-Reqs
  win_feature:
    name:
    - Web-Server
    - Web-WebServer
    - Web-Common-Http
    - Web-Default-Doc
    - Web-Dir-Browsing
    - Web-Http-Errors
    - Web-Static-Content
    - Web-Http-Redirect
    - Web-Health
    - Web-Http-Logging
    - Web-Log-Libraries
    - Web-Http-Tracing
    - Web-Performance
    - Web-Stat-Compression
    - Web-Dyn-Compression
    - Web-Security
    - Web-Filtering
    - Web-Basic-Auth
    - Web-Windows-Auth
    - Web-App-Dev
    - Web-Net-Ext45
    - Web-AppInit
    - Web-ASP
    - Web-Asp-Net45
    - Web-CGI
    - Web-ISAPI-Ext
    - Web-ISAPI-Filter
    - Web-Includes
    - Web-Mgmt-Tools
    - Web-Mgmt-Console
    - Web-Mgmt-Compat
    - Web-Metabase
    - Web-Lgcy-Mgmt-Console
    - Web-Lgcy-Scripting
    - Web-WMI
    - Web-Scripting-Tools
    - NET-Framework-Features
    - NET-Framework-45-Features
    - NET-Framework-45-Core
    - NET-Framework-45-ASPNET
    - NET-WCF-Services45
    - NET-WCF-HTTP-Activation45
    - NET-WCF-TCP-PortSharing45
    - WAS
    - Telnet-Client
    state: present
  register: win_feature

- name: Reboot if features require
  win_reboot:
  when: win_feature.reboot_required

- name: Create Log Folder
  win_file:
    path: C:\Logs
    state: directory

- name: Install Storefront Components
  block:
    - win_package:
        #path: "{{ citrix_path }}\\x64\\XenDesktop Setup\\XenDesktopServerSetup.exe"
        # Change Install Folder => https://support.citrix.com/article/CTX207667/to-install-storefront-using-command-prompt
        path: "{{ citrix_path }}\\x64\\Storefront\\CitrixStoreFront-x64.exe"
        arguments: /components storefront /configure_firewall /noreboot /quiet /logpath C:\Logs
        state: present
        expected_return_code: [0, 3, 4, 3010]
        creates_path: C:\ProgramData\Citrix\Storefront Install
      register: sf_install
  rescue:
    - debug:
          msg: 'Going to reboot and try again'
    - win_reboot:
    - win_package:
        #path: "{{ citrix_path }}\\x64\\XenDesktop Setup\\XenDesktopServerSetup.exe"
        # Change Install Folder => https://support.citrix.com/article/CTX207667/to-install-storefront-using-command-prompt
        path: "{{ citrix_path }}\\x64\\Storefront\\CitrixStoreFront-x64.exe"
        arguments: /components storefront /configure_firewall /noreboot /quiet /logpath C:\Logs
        state: present
        expected_return_code: [0, 3, 4, 3010]
        creates_path: C:\ProgramData\Citrix\Storefront Install
      register: sf_install

- name: Reboot after Storefront
  win_reboot:
  when: sf_install.changed



